const MOVIES_DATA = [
  {
    id: 1,
    title: "Inception",
    genres: ["Sci-Fi", "Action", "Thriller"],
    year: 2010,
    rating: 8.8,
    duration: "2h 28m",
    director: "Christopher Nolan",
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page", "Tom Hardy"],
    description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    keywords: ["dreams", "mind-bending", "heist", "subconscious", "reality", "time"],
    poster: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: 2,
    title: "Interstellar",
    genres: ["Sci-Fi", "Drama", "Adventure"],
    year: 2014,
    rating: 8.7,
    duration: "2h 49m",
    director: "Christopher Nolan",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"],
    description: "When Earth becomes uninhabitable, a team of explorers travels through a wormhole in space in an attempt to ensure humanity's survival.",
    keywords: ["space", "wormhole", "black hole", "father-daughter", "time-dilation", "future"],
    poster: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: 3,
    title: "The Dark Knight",
    genres: ["Action", "Crime", "Drama"],
    year: 2008,
    rating: 9.0,
    duration: "2h 32m",
    director: "Christopher Nolan",
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Maggie Gyllenhaal"],
    description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    keywords: ["superhero", "joker", "gotham", "justice", "chaos", "vigilante"],
    poster: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: 4,
    title: "Spirited Away",
    genres: ["Animation", "Adventure", "Fantasy"],
    year: 2001,
    rating: 8.6,
    duration: "2h 5m",
    director: "Hayao Miyazaki",
    cast: ["Rumi Hiiragi", "Miyu Irino", "Mari Natsuki"],
    description: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.",
    keywords: ["spirits", "magic", "studio-ghibli", "witch", "monsters", "growing-up"],
    poster: "https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: 5,
    title: "The Matrix",
    genres: ["Sci-Fi", "Action"],
    year: 1999,
    rating: 8.7,
    duration: "2h 16m",
    director: "Lana Wachowski, Lilly Wachowski",
    cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss", "Hugo Weaving"],
    description: "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
    keywords: ["cyberpunk", "virtual-reality", "simulation", "hacker", "kung-fu", "dystopia"],
    poster: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: 6,
    title: "Pulp Fiction",
    genres: ["Crime", "Drama"],
    year: 1994,
    rating: 8.9,
    duration: "2h 34m",
    director: "Quentin Tarantino",
    cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson", "Bruce Willis"],
    description: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    keywords: ["nonlinear-narrative", "hitmen", "drugs", "gangster", "retro", "cult-classic"],
    poster: "https://images.unsplash.com/photo-1594909122845-11baa439b7bf?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: 7,
    title: "Parasite",
    genres: ["Thriller", "Drama", "Comedy"],
    year: 2019,
    rating: 8.5,
    duration: "2h 12m",
    director: "Bong Joon Ho",
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik"],
    description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    keywords: ["social-commentary", "con-artists", "class-struggle", "dark-comedy", "suspense", "korean"],
    poster: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: 8,
    title: "Whiplash",
    genres: ["Drama", "Music"],
    year: 2014,
    rating: 8.5,
    duration: "1h 46m",
    director: "Damien Chazelle",
    cast: ["Miles Teller", "J.K. Simmons", "Paul Reiser", "Melissa Benoist"],
    description: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
    keywords: ["jazz", "drummer", "obsession", "ambition", "mentorship", "intense"],
    poster: "https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: 9,
    title: "Spider-Man: Into the Spider-Verse",
    genres: ["Animation", "Action", "Adventure", "Sci-Fi"],
    year: 2018,
    rating: 8.4,
    duration: "1h 57m",
    director: "Bob Persichetti, Peter Ramsey, Rodney Rothman",
    cast: ["Shameik Moore", "Jake Johnson", "Hailee Steinfeld", "Mahershala Ali"],
    description: "Teen Miles Morales becomes the Spider-Man of his universe and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.",
    keywords: ["multiverse", "superhero", "comic-book", "growing-up", "hip-hop", "stylized"],
    poster: "https://images.unsplash.com/photo-1635805737707-575885ab0820?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: 10,
    title: "The Grand Budapest Hotel",
    genres: ["Comedy", "Drama", "Adventure"],
    year: 2014,
    rating: 8.1,
    duration: "1h 39m",
    director: "Wes Anderson",
    cast: ["Ralph Fiennes", "F. Murray Abraham", "Mathieu Amalric", "Adrien Brody"],
    description: "A writer relates his adventures at a renowned European resort hotel between the first and second World Wars with a concierge who is wrongly framed for murder.",
    keywords: ["aesthetic", "quirky", "hotel", "friendship", "murder-mystery", "heist"],
    poster: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: 11,
    title: "Blade Runner 2049",
    genres: ["Sci-Fi", "Action", "Drama", "Mystery"],
    year: 2017,
    rating: 8.0,
    duration: "2h 44m",
    director: "Denis Villeneuve",
    cast: ["Ryan Gosling", "Harrison Ford", "Ana de Armas", "Robin Wright"],
    description: "A new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what's left of society into chaos.",
    keywords: ["cyberpunk", "replicant", "neon", "dystopia", "existential", "detective"],
    poster: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: 12,
    title: "Knives Out",
    genres: ["Comedy", "Mystery", "Crime"],
    year: 2019,
    rating: 7.9,
    duration: "2h 10m",
    director: "Rian Johnson",
    cast: ["Daniel Craig", "Chris Evans", "Ana de Armas", "Jamie Lee Curtis"],
    description: "A detective investigates the death of the patriarch of an eccentric, combative family.",
    keywords: ["whodunit", "detective", "inheritance", "family-drama", "quirky-comedy", "mansion"],
    poster: "https://images.unsplash.com/photo-1585647347483-22b66260dfff?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: 13,
    title: "Your Name.",
    genres: ["Animation", "Drama", "Fantasy", "Romance"],
    year: 2016,
    rating: 8.4,
    duration: "1h 46m",
    director: "Makoto Shinkai",
    cast: ["Ryunosuke Kamiki", "Mone Kamishiraishi", "Ryo Narita"],
    description: "Two strangers find themselves linked in a bizarre way. When a connection is formed, will distance be the only thing to keep them apart?",
    keywords: ["body-swap", "comet", "fate", "star-crossed", "japanese", "visual-masterpiece"],
    poster: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: 14,
    title: "Get Out",
    genres: ["Horror", "Mystery", "Thriller"],
    year: 2017,
    rating: 7.8,
    duration: "1h 44m",
    director: "Jordan Peele",
    cast: ["Daniel Kaluuya", "Allison Williams", "Bradley Whitford", "Catherine Keener"],
    description: "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness about their reception eventually reaches a boiling point.",
    keywords: ["psychological-horror", "social-thriller", "suspense", "hypnosis", "mystery", "disturbing"],
    poster: "https://images.unsplash.com/photo-1505635339340-3614eca55a9a?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: 15,
    title: "Dune",
    genres: ["Sci-Fi", "Adventure", "Action", "Drama"],
    year: 2021,
    rating: 8.0,
    duration: "2h 35m",
    director: "Denis Villeneuve",
    cast: ["Timothée Chalamet", "Rebecca Ferguson", "Oscar Isaac", "Zendaya"],
    description: "A noble family becomes embroiled in a war for control over the galaxy's most valuable asset while its heir is haunted by visions of a dark future.",
    keywords: ["desert", "space-opera", "prophecy", "sandworm", "politics", "epic"],
    poster: "https://images.unsplash.com/photo-1547234935-80c7145ec969?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: 16,
    title: "The Silence of the Lambs",
    genres: ["Thriller", "Crime", "Drama", "Horror"],
    year: 1991,
    rating: 8.6,
    duration: "1h 58m",
    director: "Jonathan Demme",
    cast: ["Jodie Foster", "Anthony Hopkins", "Lawrence A. Bonney"],
    description: "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.",
    keywords: ["hannibal-lecter", "serial-killer", "fbi", "psychological-thriller", "suspense", "masterpiece"],
    poster: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: 17,
    title: "Django Unchained",
    genres: ["Action", "Drama", "Western"],
    year: 2012,
    rating: 8.4,
    duration: "2h 45m",
    director: "Quentin Tarantino",
    cast: ["Jamie Foxx", "Christoph Waltz", "Leonardo DiCaprio", "Kerry Washington"],
    description: "With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.",
    keywords: ["bounty-hunter", "revenge", "slavery", "gunfights", "tarantino", "dark-comedy"],
    poster: "https://images.unsplash.com/photo-1533240332313-0db49b439ad3?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: 18,
    title: "La La Land",
    genres: ["Romance", "Music", "Drama", "Comedy"],
    year: 2016,
    rating: 8.0,
    duration: "2h 8m",
    director: "Damien Chazelle",
    cast: ["Ryan Gosling", "Emma Stone", "Rosemarie DeWitt"],
    description: "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.",
    keywords: ["hollywood", "jazz", "musical", "dreams", "love-story", "bittersweet"],
    poster: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: 19,
    title: "Arrival",
    genres: ["Sci-Fi", "Drama", "Mystery", "Thriller"],
    year: 2016,
    rating: 7.9,
    duration: "1h 56m",
    director: "Denis Villeneuve",
    cast: ["Amy Adams", "Jeremy Renner", "Forest Whitaker"],
    description: "A linguist works with the military to communicate with alien-newcomers after twelve mysterious spacecraft appear around the world.",
    keywords: ["aliens", "linguistics", "time", "first-contact", "grief", "mind-bending"],
    poster: "https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: 20,
    title: "Everything Everywhere All at Once",
    genres: ["Action", "Adventure", "Comedy", "Sci-Fi", "Fantasy"],
    year: 2022,
    rating: 8.5,
    duration: "2h 19m",
    director: "Daniel Kwan, Daniel Scheinert",
    cast: ["Michelle Yeoh", "Stephanie Hsu", "Ke Huy Quan", "Jamie Lee Curtis"],
    description: "A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes and connecting with the lives she could have led.",
    keywords: ["multiverse", "existentialism", "mother-daughter", "absurdist", "martial-arts", "masterpiece"],
    poster: "https://images.unsplash.com/photo-1461360370896-922624d12aa1?auto=format&fit=crop&w=600&q=80"
  }
];
